# Generated by Django 4.2.3 on 2023-07-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_message_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_text', models.TextField(max_length=200)),
                ('uploaded_image', models.ImageField(upload_to='ocr_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
