# Generated by Django 4.2.3 on 2023-07-24 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_ocrimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_images', to='profiles.profile'),
        ),
    ]
