# Generated by Django 4.2.3 on 2023-07-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_ocrimage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrimage',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
