# Generated by Django 4.2.3 on 2023-07-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_ocrimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrimage',
            name='fully_segmented_image',
            field=models.ImageField(default=None, upload_to='media/fully_segmented_images/'),
        ),
        migrations.AlterField(
            model_name='ocrimage',
            name='uploaded_image',
            field=models.ImageField(upload_to='media/ocr_images/'),
        ),
    ]
