# Generated by Django 4.2.3 on 2023-07-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_ocrimage_fully_segmented_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrimage',
            name='fully_segmented_image',
            field=models.ImageField(default='media/avatar.png', upload_to='media/fully_segmented_images/'),
        ),
    ]
