# Generated by Django 4.2.3 on 2023-07-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_ocrimage_fully_segmented_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrimage',
            name='fully_segmented_image',
        ),
    ]
