# Generated by Django 4.2.3 on 2023-07-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrimage',
            name='isSnipped',
            field=models.BooleanField(default=False),
        ),
    ]
